.update-json-files-base:
  stage: Update JSON Files
  image: python:3.11
  tags:
    - legora
  before_script:
    - python -m pip install --upgrade pip
    - python3.11 -m venv legora
    - source legora/bin/activate
    - pip install requests beautifulsoup4
    - git config --global user.name "Vinsuka"
    - git config --global user.email "dunith.20200471@iit.ac.lk"
  after_script:
    - echo "Committing JSON file changes"
    - git commit -m "Update JSON files" || echo "No changes to commit"
    - git push https://oauth2:$GITLAB_TOKEN@gitlab.com/shakthiraveen2002/Legora-standord.git HEAD:$CI_COMMIT_REF_NAME || echo "No changes to push"

update-appeal-court-json:
  extends: .update-json-files-base
  script:
    - echo "Updating JSON files"
    - sleep 10
    - echo "JSON files updated"
    - git add ETL/scrapers/appeal-court-pages.json
  artifacts:
    paths:
      - ETL/scrapers/appeal-court-pages.json

update-supreme-court-json:
  extends: .update-json-files-base
  script:
    - echo "Updating Supreme Court JSON file"
    - python ETL/scrapers/update_supreme_court_json.py
    - git add ETL/scrapers/supreme_court_run.json
  artifacts:
    paths:
      - ETL/scrapers/supreme_court_run.json
